import {
  getAllMessages,
  deleteMessage,
  storeMessage,
  messagesRef,
  signInAsAdmin,
  auth,
  uploadImage,
  getAllProducts,
  storeProduct,
  markMessageAsRead,
  markMessageAsUnread,
  getProductById,
  deleteProduct,
  saveEmail,
} from './firebase'
export {
  getAllMessages,
  deleteMessage,
  storeMessage,
  messagesRef,
  signInAsAdmin,
  auth,
  uploadImage,
  getAllProducts,
  storeProduct,
  markMessageAsRead,
  markMessageAsUnread,
  getProductById,
  deleteProduct,
  saveEmail,
}
